import localFont from "next/font/local";
import "./globals.css";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ThemeProvider } from 'next-themes';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const tva2012 = localFont({
  src: "./fonts/Tva2012.ttf",
  variable: "--font-tva",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${tva2012.variable} antialiased`} >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar/>
            <div>{children}</div>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
